name: phoenixweather_bloc_common
description: part of program, that can be reused in dart frameworks
author: bgoncharuck
licence: LGPL v3
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  bloc: ^4.0.0
  equatable: ^1.2.0
  rxdart: ^0.24.1
  
  phoenixweather_common:
    path: ../phoenixweather_common